apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: flink

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: flink-role
 namespace: flink
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*","controllerrevisions"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: flink-role-binding1
 namespace: flink
subjects:
- kind: ServiceAccount
  name: flink
  namespace: flink
roleRef:
  kind: ClusterRole
  name: flink-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: flink-role-binding2
 namespace: flink
subjects:
- kind: ServiceAccount
  name: default
  namespace: flink
roleRef:
  kind: ClusterRole
  name: flink-role
  apiGroup: rbac.authorization.k8s.io

# ---
#
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#  name: flink-role-binding2
#  namespace: flink-ns
# subjects:
# - kind: ServiceAccount
#   name: flink-sa
#   namespace: default
# roleRef:
#   kind: ClusterRole
#   name: flink-role
#   apiGroup: rbac.authorization.k8s.io
