apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flinkjobcluster-sample
spec:
  image:
    name: flink:1.10.1-scala_2.12
  envVars:
    - name: CHECK_POINTING_PATH
      value: "file:///tmp/"
    - name: FLINK_LOG_PREFIX
      value: "/opt/flink/"
    - name: KAFKA_HOST
      value: "kafka-host"
    - name: KAFKA_PORT
      value: "9094"
  jobManager:
    ports:
      ui: 8081
    resources:
      limits:
        memory: "1024Mi"
        cpu: "200m"
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: "2048Mi"
        cpu: "400m"
  job:
    jarFile: ./examples/streaming/WordCount.jar
    className: org.apache.flink.streaming.examples.wordcount.WordCount
    parallelism: 1
    resources:
      limits:
        memory: "1024Mi"
        cpu: "200m"
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
    classloader.resolve-order: "parent-first"

