apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flinkjobcluster-sample
spec:
  image:
    name: piyushdocker/flink_kakfa_kubeexample
  envVars:
    - name: CHECK_POINTING_PATH
      value: "file:///tmp/"
    - name: FLINK_LOG_PREFIX
      value: "/opt/flink/"
    - name: KAFKA_HOST
      value: "kafka-cp-kafka.default"
    - name: KAFKA_PORT
      value: "9092"
  jobManager:
    ports:
      ui: 8081
    resources:
      limits:
        memory: "600Mi"
        cpu: "200m"
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: "2048Mi"
        cpu: "400m"
  job:
    jarFile: /opt/flink/app.jar
    className: Job
    parallelism: 1
    resources:
      limits:
        memory: "500Mi"
        cpu: "200m"
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
    classloader.resolve-order: "parent-first"

