---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    app: schema-registry-svc
spec:
  ports:
  - port: 8081
  clusterIP: None
  selector:
    app: schema-registry
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: schema-registry
spec:
  serviceName: schema-registry-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - schema-registry
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: schema-registry
        imagePullPolicy: IfNotPresent
        image: confluentinc/cp-schema-registry:4.1.0
        resources:
          requests:
            memory: "2Gi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "400m"
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: "schema-registry"
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: "zookeeper-0.zookeeper-svc:2181"
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/schema-registry
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
